와이어프레임 구현중입니다
Comp-ACT/random-lunch-menu-front pull request #5
Opened 2022-07-25 15:43 UTC by Ji-InPark

## 📚 개요

> 와이어 프레임 구현중입니다.

## ❗❗ 중요한 변경점(Option)

> 웹 페이지 크기를 아직 제대로 못정해서 더 좋은 의견있으면 코멘트 부탁드립니다.

2022-07-26 14:57 UTC, sejoon00 requested changes

2022-07-26 14:57 UTC, sejoon00 commented on src/components/pages/Home.jsx
> +      <div style={{ width: '15%' }}>
사이드 바 나중에는 퍼센트로 하지말고 크기고정으로 화면이 특정 픽셀보다 작아지면 껐다 킬수 있는걸로 해주세요

2022-07-26 14:57 UTC, sejoon00 commented on src/components/common/Roulette.jsx
> +    <div style={{ background: Colors.OLDLACE, height: '100%' }}>
홈화면 크기는 네이버 따라 갑시다

2022-07-26 14:59 UTC, sejoon00 commented on src/components/common/Roulette.jsx
> +    <div style={{ background: Colors.OLDLACE, height: '100%' }}>
생각해보니까 우리는 옆에 방 설정하는게 있으니 네이버 따라가면 이상할것 같네요. 음.. Roulette안에서 적당히 양옆 공백 있으면 좋을 것 같습니다

2022-07-26 15:00 UTC, Ji-InPark commented on src/components/common/Roulette.jsx
> +    <div style={{ background: Colors.OLDLACE, height: '100%' }}>
아직은 와이어프레임 구현중이라서 해당 부분은 룰렛 구현하면서 반영할게요~ :)

2022-07-26 15:02 UTC, Ji-InPark commented on src/components/pages/Home.jsx
> +      <div style={{ width: '15%' }}>
사이드 바 토글 방식으로 진행해보겠습니다~

2022-07-26 15:02 UTC, sejoon00 commented on src/components/pages/Home.jsx
> +      <div style={{ width: '15%' }}>
넴~

2022-07-27 14:44 UTC, sejoon00 approved these changes
LGTM

2022-07-27 14:50 UTC, sejoon00 approved these changes

2022-07-27 14:54 UTC, merged